pipeline {
    agent any

    environment {
        foo = 'bar'
    }

    stages {

        stage('Clear Previous Builds') {
            steps {
                echo 'Clearing previous builds...'
                dir('play-with-devsecops') {
                    sh 'rm -rf target/*'
                }
                echo 'Previous builds cleared.'
            }
        }

        stage('Prepare Workspace') {
            steps {
                echo 'Preparing workspace...'
                dir('play-with-devsecops') {
                    sh 'ls -al'
                }
            }
        }
        stage('Compile') {
            steps {
                echo 'Compiling the project...'
                dir('play-with-devsecops') {
                    sh 'mvn compile'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Running unit tests...'
                dir('play-with-devsecops') {
                    sh 'mvn test'
                }
            }
        }
        stage('Package') {
            steps {
                input message: 'Do you want to proceed with packaging?', ok: 'Yes, package it!'
                echo 'Packaging the project...'
                dir('play-with-devsecops') {
                    sh 'mvn install'
                }
            }
        }
        stage('Collect Reports') {
            steps {
                echo 'Archiving test and analysis reports...'
                dir('play-with-devsecops') {
                    junit '**/target/surefire-reports/*.xml'
                    archiveArtifacts artifacts: '**/target/**', fingerprint: true
                }
            }
        }
    }
    post {
            success {
                echo '✅ Build completed successfully!'
            }
            failure {
                echo '❌ Build failed. Check logs for details.'
            }
            always {
                echo '📦 Pipeline execution finished.'
            }
        }
    }
