
pipeline {
    agent any
    tools {
        maven 'Maven 3'
        jdk 'Java 17'
    }
    stages {
        stage('Build') {
            steps {
                script {
                    // Example build step
                    echo 'Building the project...'
                    sh 'mvn -v'

                }
                dir('play-with-devsecops') {
                    // Example step to list files in the src directory
                    sh 'ls -l'
                    // Example step to run Maven build
                    sh 'mvn clean package'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    // Example test step
                    echo 'Running tests...'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // Example deployment step
                    echo 'Deploying the application...'
                }
            }
        }
    }
}