
pipeline{
    agent any
    stages{
        stage("java-build"){
            steps{
                dir('docker-k8s/services/java-web-service'){
                    sh 'mvn clean package'
                }
            }
        }
        stage("docker-build"){
            steps{
                dir('docker-k8s/services/java-web-service'){
                    sh 'docker build -t java-web-service .'
                }
            }
        }
    }
}